package templates

const fileTpl = `// Code generated by aws-grpc-service-proxy. DO NOT EDIT.

package {{ pkg . }}

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"math"
	"net"
	"time"

	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/lambda"
	"github.com/golang/protobuf/jsonpb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"
	grpc_zap "github.com/grpc-ecosystem/go-grpc-middleware/logging/zap"
  "github.com/aws/aws-sdk-go/aws"
  "github.com/aws/aws-sdk-go/service/dynamodb"
  status "google.golang.org/grpc/status"
  "go.uber.org/zap"
  grpc_middleware "github.com/grpc-ecosystem/go-grpc-middleware"

  "github.com/katallaxie/protoc-gen-cloud-proxy/pkg/proxy"
  o "github.com/katallaxie/protoc-gen-cloud-proxy/pkg/opts"
)
`
