package templates

const fileTpl = `// Code generated by aws-grpc-service-proxy. DO NOT EDIT.

package {{ pkg . }}

import (
	"time"
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"math"
	"net"

  "github.com/katallaxie/protoc-gen-cloud-proxy/pkg/proxy"
  o "github.com/katallaxie/protoc-gen-cloud-proxy/pkg/opts"

	"github.com/golang/protobuf/jsonpb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"
  "github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/lambda"
  "github.com/aws/aws-sdk-go/service/dynamodb"
)
`
