// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: api/fields.proto

package annotations

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Fields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Types that are assignable to Pattern:
	//	*Fields_Dynamodb
	Pattern isFields_Pattern `protobuf_oneof:"pattern"`
}

func (x *Fields) Reset() {
	*x = Fields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fields) ProtoMessage() {}

func (x *Fields) ProtoReflect() protoreflect.Message {
	mi := &file_api_fields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fields.ProtoReflect.Descriptor instead.
func (*Fields) Descriptor() ([]byte, []int) {
	return file_api_fields_proto_rawDescGZIP(), []int{0}
}

func (x *Fields) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (m *Fields) GetPattern() isFields_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (x *Fields) GetDynamodb() *Fields_DynamoDB {
	if x, ok := x.GetPattern().(*Fields_Dynamodb); ok {
		return x.Dynamodb
	}
	return nil
}

type isFields_Pattern interface {
	isFields_Pattern()
}

type Fields_Dynamodb struct {
	Dynamodb *Fields_DynamoDB `protobuf:"bytes,10,opt,name=dynamodb,proto3,oneof"`
}

func (*Fields_Dynamodb) isFields_Pattern() {}

type Fields_DynamoDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpressionValue string `protobuf:"bytes,1,opt,name=ExpressionValue,proto3" json:"ExpressionValue,omitempty"`
	Key             string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *Fields_DynamoDB) Reset() {
	*x = Fields_DynamoDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fields_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fields_DynamoDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fields_DynamoDB) ProtoMessage() {}

func (x *Fields_DynamoDB) ProtoReflect() protoreflect.Message {
	mi := &file_api_fields_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fields_DynamoDB.ProtoReflect.Descriptor instead.
func (*Fields_DynamoDB) Descriptor() ([]byte, []int) {
	return file_api_fields_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Fields_DynamoDB) GetExpressionValue() string {
	if x != nil {
		return x.ExpressionValue
	}
	return ""
}

func (x *Fields_DynamoDB) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_api_fields_proto protoreflect.FileDescriptor

var file_api_fields_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6d, 0x61, 0x7a, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xb2,
	0x01, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x39, 0x0a, 0x08, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x64,
	0x62, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x6f, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x6f, 0x44, 0x42, 0x48, 0x00, 0x52, 0x08, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x64, 0x62,
	0x1a, 0x46, 0x0a, 0x08, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x44, 0x42, 0x12, 0x28, 0x0a, 0x0f,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x42, 0x14, 0x5a, 0x0f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0xf8, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_fields_proto_rawDescOnce sync.Once
	file_api_fields_proto_rawDescData = file_api_fields_proto_rawDesc
)

func file_api_fields_proto_rawDescGZIP() []byte {
	file_api_fields_proto_rawDescOnce.Do(func() {
		file_api_fields_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_fields_proto_rawDescData)
	})
	return file_api_fields_proto_rawDescData
}

var file_api_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_fields_proto_goTypes = []interface{}{
	(*Fields)(nil),          // 0: amazon.api.Fields
	(*Fields_DynamoDB)(nil), // 1: amazon.api.Fields.DynamoDB
}
var file_api_fields_proto_depIdxs = []int32{
	1, // 0: amazon.api.Fields.dynamodb:type_name -> amazon.api.Fields.DynamoDB
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_fields_proto_init() }
func file_api_fields_proto_init() {
	if File_api_fields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_fields_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_fields_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fields_DynamoDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_fields_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Fields_Dynamodb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_fields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_fields_proto_goTypes,
		DependencyIndexes: file_api_fields_proto_depIdxs,
		MessageInfos:      file_api_fields_proto_msgTypes,
	}.Build()
	File_api_fields_proto = out.File
	file_api_fields_proto_rawDesc = nil
	file_api_fields_proto_goTypes = nil
	file_api_fields_proto_depIdxs = nil
}
