// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: sqs.proto

package annotations

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// SQS message ...
type Sqs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sqs) Reset() {
	*x = Sqs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sqs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sqs) ProtoMessage() {}

func (x *Sqs) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sqs.ProtoReflect.Descriptor instead.
func (*Sqs) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{0}
}

// Input message ...
type Sqs_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageAttributeNames   []string `protobuf:"bytes,1,rep,name=MessageAttributeNames,proto3" json:"MessageAttributeNames,omitempty"`
	QueueUrl                string   `protobuf:"bytes,2,opt,name=QueueUrl,proto3" json:"QueueUrl,omitempty"`
	ReceiveRequestAttemptId string   `protobuf:"bytes,3,opt,name=ReceiveRequestAttemptId,proto3" json:"ReceiveRequestAttemptId,omitempty"`
	VisibilityTimeout       int64    `protobuf:"varint,4,opt,name=VisibilityTimeout,proto3" json:"VisibilityTimeout,omitempty"`
	WaitTimeSeconds         int64    `protobuf:"varint,5,opt,name=WaitTimeSeconds,proto3" json:"WaitTimeSeconds,omitempty"`
}

func (x *Sqs_Input) Reset() {
	*x = Sqs_Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sqs_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sqs_Input) ProtoMessage() {}

func (x *Sqs_Input) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sqs_Input.ProtoReflect.Descriptor instead.
func (*Sqs_Input) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Sqs_Input) GetMessageAttributeNames() []string {
	if x != nil {
		return x.MessageAttributeNames
	}
	return nil
}

func (x *Sqs_Input) GetQueueUrl() string {
	if x != nil {
		return x.QueueUrl
	}
	return ""
}

func (x *Sqs_Input) GetReceiveRequestAttemptId() string {
	if x != nil {
		return x.ReceiveRequestAttemptId
	}
	return ""
}

func (x *Sqs_Input) GetVisibilityTimeout() int64 {
	if x != nil {
		return x.VisibilityTimeout
	}
	return 0
}

func (x *Sqs_Input) GetWaitTimeSeconds() int64 {
	if x != nil {
		return x.WaitTimeSeconds
	}
	return 0
}

// Output message ..
type Sqs_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MD5OfMessageAttributes       string `protobuf:"bytes,1,opt,name=MD5OfMessageAttributes,proto3" json:"MD5OfMessageAttributes,omitempty"`
	MD5OfMessageBody             string `protobuf:"bytes,2,opt,name=MD5OfMessageBody,proto3" json:"MD5OfMessageBody,omitempty"`
	MD5OfMessageSystemAttributes string `protobuf:"bytes,3,opt,name=MD5OfMessageSystemAttributes,proto3" json:"MD5OfMessageSystemAttributes,omitempty"`
	MessageId                    string `protobuf:"bytes,4,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	SequenceNumber               string `protobuf:"bytes,5,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
}

func (x *Sqs_Output) Reset() {
	*x = Sqs_Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sqs_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sqs_Output) ProtoMessage() {}

func (x *Sqs_Output) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sqs_Output.ProtoReflect.Descriptor instead.
func (*Sqs_Output) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Sqs_Output) GetMD5OfMessageAttributes() string {
	if x != nil {
		return x.MD5OfMessageAttributes
	}
	return ""
}

func (x *Sqs_Output) GetMD5OfMessageBody() string {
	if x != nil {
		return x.MD5OfMessageBody
	}
	return ""
}

func (x *Sqs_Output) GetMD5OfMessageSystemAttributes() string {
	if x != nil {
		return x.MD5OfMessageSystemAttributes
	}
	return ""
}

func (x *Sqs_Output) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Sqs_Output) GetSequenceNumber() string {
	if x != nil {
		return x.SequenceNumber
	}
	return ""
}

var File_sqs_proto protoreflect.FileDescriptor

var file_sqs_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x71, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6d, 0x61,
	0x7a, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xec, 0x03, 0x0a, 0x03, 0x53, 0x71, 0x73, 0x1a,
	0xeb, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x15, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x38, 0x0a, 0x17, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x74, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x56, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x57, 0x61,
	0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x1a, 0xf6, 0x01,
	0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x4d, 0x44, 0x35, 0x4f,
	0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x4d, 0x44, 0x35, 0x4f, 0x66, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x12, 0x2a, 0x0a, 0x10, 0x4d, 0x44, 0x35, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x4d, 0x44, 0x35, 0x4f,
	0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x42, 0x0a, 0x1c,
	0x4d, 0x44, 0x35, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x1c, 0x4d, 0x44, 0x35, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x78, 0x69, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sqs_proto_rawDescOnce sync.Once
	file_sqs_proto_rawDescData = file_sqs_proto_rawDesc
)

func file_sqs_proto_rawDescGZIP() []byte {
	file_sqs_proto_rawDescOnce.Do(func() {
		file_sqs_proto_rawDescData = protoimpl.X.CompressGZIP(file_sqs_proto_rawDescData)
	})
	return file_sqs_proto_rawDescData
}

var file_sqs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sqs_proto_goTypes = []interface{}{
	(*Sqs)(nil),        // 0: amazon.api.Sqs
	(*Sqs_Input)(nil),  // 1: amazon.api.Sqs.Input
	(*Sqs_Output)(nil), // 2: amazon.api.Sqs.Output
}
var file_sqs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sqs_proto_init() }
func file_sqs_proto_init() {
	if File_sqs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sqs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sqs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sqs_Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sqs_Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sqs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqs_proto_goTypes,
		DependencyIndexes: file_sqs_proto_depIdxs,
		MessageInfos:      file_sqs_proto_msgTypes,
	}.Build()
	File_sqs_proto = out.File
	file_sqs_proto_rawDesc = nil
	file_sqs_proto_goTypes = nil
	file_sqs_proto_depIdxs = nil
}
